main: skyzen.lobby.Lobby

name: Smashs
version: 1.0
author: Skyzen

commands:
  money:
    description: Commande des coins
    aliases: [coins]
  msg:
    description: Messages privées
  grade:
    description: Commande des grades
    aliases: [rank]