main: skyzen.lobby.Lobby

name: Smashs
version: 1.0
author: Skyzen

commands:
  coins:
    description: Commande des coins
  msg:
    description: Messages privées
  grade:
    description: Commande des grades
    aliases: [rank]
  jeux:
      description: Commande des jeux
  tp:
    description: Commande de tp
  list:
    description: Commande de list
  ban:
    description: Commande de ban
  bowdragon:
    description: Commande de jeux BowDragon